### Travis CI Build


# config

branches:
  only:
    - gh-pages

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

language: ruby

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"

rvm:
  - 2.2.1

sudo: false


# script

before_script:
  - gem install bundler
  - bundle install
  - npm install

script:
  - npm run build
  - npm run test
